# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d8e00b805f4642ed99e9dd2ec045ab2570ecc104fdc2b7363b06e455adbc1bfcf87f289c85e9566e6823158af52f72474e60bd555fc775a2de490602bcfc060

test:
  secret_key_base: ac5d899b9d7e69f0e23c5afd8a16d02b445d5239ef401b96e3965ea832af134e65445bd8874dd404e9b1b011d460bb1fcab9d577bdc3be2d352218ad06f81def

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
